/*
 * Created on 17 oct. 2016 ( Time 17:17:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package fr.lidadi.jee.eventmanager.dao.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "EVENT_PERSONN_PARTICIPANTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EVENT_PERSONN_PARTICIPANTS", schema="EVENTMANAGER" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EventPersonnParticipantsEntity.countAll", query="SELECT COUNT(x) FROM EventPersonnParticipantsEntity x" )
} )
public class EventPersonnParticipantsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private EventPersonnParticipantsEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventPersonnParticipantsEntity() {
		super();
		this.compositePrimaryKey = new EventPersonnParticipantsEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setEventId( byte[] eventId ) {
        this.compositePrimaryKey.setEventId( eventId ) ;
    }
    public byte[] getEventId() {
        return this.compositePrimaryKey.getEventId() ;
    }
    public void setPersonnId( byte[] personnId ) {
        this.compositePrimaryKey.setPersonnId( personnId ) ;
    }
    public byte[] getPersonnId() {
        return this.compositePrimaryKey.getPersonnId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
