/*
 * Created on 17 oct. 2016 ( Time 17:17:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.lidadi.jee.eventmanager.dao.jpa;

import java.io.Serializable;
import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Lob;

/**
 * Composite primary key for entity "EventPersonnOwnerEntity" ( stored in table
 * "EVENT_PERSONN_OWNER" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class EventPersonnOwnerEntityKey implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY KEY ATTRIBUTES
	// ----------------------------------------------------------------------
	@Lob
	@Column(name = "EVENT_ID", nullable = false)
	private byte[] eventId;

	@Lob
	@Column(name = "PERSONN_ID", nullable = false)
	private byte[] personnId;

	// ----------------------------------------------------------------------
	// CONSTRUCTORS
	// ----------------------------------------------------------------------
	public EventPersonnOwnerEntityKey() {
		super();
	}

	public EventPersonnOwnerEntityKey(byte[] eventId, byte[] personnId) {
		super();
		this.eventId = eventId;
		this.personnId = personnId;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR KEY FIELDS
	// ----------------------------------------------------------------------
	public void setEventId(byte[] value) {
		this.eventId = value;
	}

	public byte[] getEventId() {
		return this.eventId;
	}

	public void setPersonnId(byte[] value) {
		this.personnId = value;
	}

	public byte[] getPersonnId() {
		return this.personnId;
	}

	// ----------------------------------------------------------------------
	// equals METHOD
	// ----------------------------------------------------------------------
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (this.getClass() != obj.getClass())
			return false;
		EventPersonnOwnerEntityKey other = (EventPersonnOwnerEntityKey) obj;
		// --- Attribute eventId
		if (!Arrays.equals(eventId, other.eventId))
			return false;
		// --- Attribute personnId
		if (!Arrays.equals(personnId, other.personnId))
			return false;
		return true;
	}

	// ----------------------------------------------------------------------
	// hashCode METHOD
	// ----------------------------------------------------------------------
	public int hashCode() {
		final int prime = 31;
		int result = 1;

		// --- Attribute eventId
		result = prime * result + Arrays.hashCode(eventId);
		// --- Attribute personnId
		result = prime * result + Arrays.hashCode(personnId);

		return result;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(eventId);
		sb.append("|");
		sb.append(personnId);
		return sb.toString();
	}
}
