/*
 * Created on 17 oct. 2016 ( Time 17:17:31 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.lidadi.jee.eventmanager.dao.jpa;

import java.io.Serializable;
import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Lob;

/**
 * Composite primary key for entity "ParticipantEntity" ( stored in table
 * "PARTICIPANT" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class ParticipantEntityKey implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY KEY ATTRIBUTES
	// ----------------------------------------------------------------------
	@Lob
	@Column(name = "EVENT_ID", nullable = false)
	private byte[] eventId;

	@Column(name = "MAIL", nullable = false, length = 255)
	private String mail;

	// ----------------------------------------------------------------------
	// CONSTRUCTORS
	// ----------------------------------------------------------------------
	public ParticipantEntityKey() {
		super();
	}

	public ParticipantEntityKey(byte[] eventId, String mail) {
		super();
		this.eventId = eventId;
		this.mail = mail;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR KEY FIELDS
	// ----------------------------------------------------------------------
	public void setEventId(byte[] value) {
		this.eventId = value;
	}

	public byte[] getEventId() {
		return this.eventId;
	}

	public void setMail(String value) {
		this.mail = value;
	}

	public String getMail() {
		return this.mail;
	}

	// ----------------------------------------------------------------------
	// equals METHOD
	// ----------------------------------------------------------------------
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (this.getClass() != obj.getClass())
			return false;
		ParticipantEntityKey other = (ParticipantEntityKey) obj;
		// --- Attribute eventId
		if (!Arrays.equals(eventId, other.eventId))
			return false;
		// --- Attribute mail
		if (mail == null) {
			if (other.mail != null)
				return false;
		} else if (!mail.equals(other.mail))
			return false;
		return true;
	}

	// ----------------------------------------------------------------------
	// hashCode METHOD
	// ----------------------------------------------------------------------
	public int hashCode() {
		final int prime = 31;
		int result = 1;

		// --- Attribute eventId
		result = prime * result + Arrays.hashCode(eventId);
		// --- Attribute mail
		result = prime * result + ((mail == null) ? 0 : mail.hashCode());

		return result;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(eventId);
		sb.append("|");
		sb.append(mail);
		return sb.toString();
	}
}
