/*
 * Created on 17 oct. 2016 ( Time 17:17:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package fr.lidadi.jee.eventmanager.dao.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "SLUG"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="SLUG", schema="EVENTMANAGER" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SlugEntity.countAll", query="SELECT COUNT(x) FROM SlugEntity x" )
} )
public class SlugEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private SlugEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="EVENT_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private EventEntity event       ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SlugEntity() {
		super();
		this.compositePrimaryKey = new SlugEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setEventId( byte[] eventId ) {
        this.compositePrimaryKey.setEventId( eventId ) ;
    }
    public byte[] getEventId() {
        return this.compositePrimaryKey.getEventId() ;
    }
    public void setSlug( String slug ) {
        this.compositePrimaryKey.setSlug( slug ) ;
    }
    public String getSlug() {
        return this.compositePrimaryKey.getSlug() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEvent( EventEntity event ) {
        this.event = event;
    }
    public EventEntity getEvent() {
        return this.event;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
