/*
 * Created on 17 oct. 2016 ( Time 17:17:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key


package fr.lidadi.jee.eventmanager.app.slug;

import fr.lidadi.jee.eventmanager.app.event.EventEntity;
import fr.lidadi.jee.eventmanager.dao.Entity;

import java.io.Serializable;
import java.util.UUID;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import javax.persistence.*;


/**
 * Persistent class for entity stored in table "SLUG"
 *
 * @author Telosys Tools Generator
 *
 */

@javax.persistence.Entity(name="slug")
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="SlugEntity.findAll", query="SELECT x FROM slug x" )
//} )
public class SlugEntity implements Entity {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
    //----------------------------------------------------------------------
	@EmbeddedId
    private SlugEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="EVENT_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private EventEntity event       ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SlugEntity() {
		super();
		this.compositePrimaryKey = new SlugEntityKey();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY
    //----------------------------------------------------------------------
    public void setEventId( UUID eventId ) {
        this.compositePrimaryKey.setEventId( eventId ) ;
    }
    public UUID getEventId() {
        return this.compositePrimaryKey.getEventId() ;
    }
    public void setSlug( String slug ) {
        this.compositePrimaryKey.setSlug( slug ) ;
    }
    public String getSlug() {
        return this.compositePrimaryKey.getSlug() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEvent( EventEntity event ) {
        this.event = event;
    }
    public EventEntity getEvent() {
        return this.event;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        if ( compositePrimaryKey != null ) {
            sb.append(compositePrimaryKey.toString());
        }
        else {
            sb.append( "(null-key)" );
        }
        sb.append("]:");
        return sb.toString();
    }

    @Override
    public Object getPrimaryKey() {
        return compositePrimaryKey;
    }


    @Embeddable
    public class SlugEntityKey implements Serializable {
        private static final long serialVersionUID = 1L;

        // ----------------------------------------------------------------------
        // ENTITY KEY ATTRIBUTES
        // ----------------------------------------------------------------------
        @Lob
        @Column(name = "EVENT_ID", nullable = false)
        private UUID eventId;

        @Column(name = "SLUG", nullable = false, length = 255)
        private String slug;

        // ----------------------------------------------------------------------
        // CONSTRUCTORS
        // ----------------------------------------------------------------------
        public SlugEntityKey() {
            super();
        }

        public SlugEntityKey(UUID eventId, String slug) {
            super();
            this.eventId = eventId;
            this.slug = slug;
        }

        // ----------------------------------------------------------------------
        // GETTERS & SETTERS FOR KEY FIELDS
        // ----------------------------------------------------------------------
        public void setEventId(UUID value) {
            this.eventId = value;
        }

        public UUID getEventId() {
            return this.eventId;
        }

        public void setSlug(String value) {
            this.slug = value;
        }

        public String getSlug() {
            return this.slug;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            SlugEntityKey that = (SlugEntityKey) o;

            if (getEventId() != null ? !getEventId().equals(that.getEventId()) : that.getEventId() != null)
                return false;
            return getSlug() != null ? getSlug().equals(that.getSlug()) : that.getSlug() == null;

        }

        @Override
        public int hashCode() {
            int result = getEventId() != null ? getEventId().hashCode() : 0;
            result = 31 * result + (getSlug() != null ? getSlug().hashCode() : 0);
            return result;
        }

        // ----------------------------------------------------------------------
        // toString METHOD
        // ----------------------------------------------------------------------
        public String toString() {
            StringBuffer sb = new StringBuffer();
            sb.append(eventId);
            sb.append("|");
            sb.append(slug);
            return sb.toString();
        }
    }

}
