/*
 * Created on 17 oct. 2016 ( Time 17:17:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key


package fr.lidadi.jee.eventmanager.app.eventpersonowner;

import java.io.Serializable;
import java.util.UUID;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;
import javax.persistence.Entity;

/**
 * Persistent class for entity stored in table "EVENT_Person_PARTICIPANTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity(name="eventpersonparticipants")
public class EventPersonParticipants implements fr.lidadi.jee.eventmanager.framework.dao.Entity {

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
    //----------------------------------------------------------------------
	@EmbeddedId
    private EventPersonParticipantsKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventPersonParticipants() {
		super();
		this.compositePrimaryKey = new EventPersonParticipantsKey();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY
    //----------------------------------------------------------------------
    public void setEventId( UUID eventId ) {
        this.compositePrimaryKey.setEventId( eventId ) ;
    }
    public UUID getEventId() {
        return this.compositePrimaryKey.getEventId() ;
    }
    public void setPersonId( UUID personId ) {
        this.compositePrimaryKey.setPersonId( personId ) ;
    }
    public UUID getPersonId() {
        return this.compositePrimaryKey.getPersonId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        if ( compositePrimaryKey != null ) {
            sb.append(compositePrimaryKey.toString());
        }
        else {
            sb.append( "(null-key)" );
        }
        sb.append("]:");
        return sb.toString();
    }

    @Override
    public Object getPrimaryKey() {
        return null;
    }

    @Embeddable
    public class EventPersonParticipantsKey implements Serializable {
        private static final long serialVersionUID = 1L;

        // ----------------------------------------------------------------------
        // ENTITY KEY ATTRIBUTES
        // ----------------------------------------------------------------------
        @Lob
        @Column(name = "EVENT_ID", nullable = false)
        private UUID eventId;

        @Lob
        @Column(name = "Person_ID", nullable = false)
        private UUID personId;

        // ----------------------------------------------------------------------
        // CONSTRUCTORS
        // ----------------------------------------------------------------------
        public EventPersonParticipantsKey() {
            super();
        }

        public EventPersonParticipantsKey(UUID eventId, UUID personId) {
            super();
            this.eventId = eventId;
            this.personId = personId;
        }

        // ----------------------------------------------------------------------
        // GETTERS & SETTERS FOR KEY FIELDS
        // ----------------------------------------------------------------------
        public void setEventId(UUID value) {
            this.eventId = value;
        }

        public UUID getEventId() {
            return this.eventId;
        }

        public void setPersonId(UUID value) {
            this.personId = value;
        }

        public UUID getPersonId() {
            return this.personId;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            EventPersonParticipantsKey that = (EventPersonParticipantsKey) o;

            if (getEventId() != null ? !getEventId().equals(that.getEventId()) : that.getEventId() != null)
                return false;
            return getPersonId() != null ? getPersonId().equals(that.getPersonId()) : that.getPersonId() == null;

        }

        @Override
        public int hashCode() {
            int result = getEventId() != null ? getEventId().hashCode() : 0;
            result = 31 * result + (getPersonId() != null ? getPersonId().hashCode() : 0);
            return result;
        }

        // ----------------------------------------------------------------------
        // toString METHOD
        // ----------------------------------------------------------------------
        public String toString() {
            StringBuffer sb = new StringBuffer();
            sb.append(eventId);
            sb.append("|");
            sb.append(personId);
            return sb.toString();
        }
    }

}
